name: 'Get and Cache Dependencies'
description: 'Get depencies via npm and cache them.'
inputs:
  #allow uses whether deps should be installed. turn off caching
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default:  'true'
outputs:
  used-cache:
    description: 'Whether the Cache was used.'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching =='true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching.caching != 'true'
      run: | 
        npm ci
        echo: "::set-output name=cache::'${{ inputs.caching }}'"
      shell: bash #shell to be used when executing this step